version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "3003:3003"
    environment:
      OPENWEATHERMAP_API_URL: ${OPENWEATHERMAP_API_URL}
      OPENWEATHERMAP_API_KEY: ${OPENWEATHERMAP_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_URL: ${OPENAI_API_URL}
    volumes:
      - .:/app
    command: ["fastapi", "run", "--host", "0.0.0.0", "src/main.py"]
