[project]
name = "kawaii-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi-cache2>=0.2.2",
    "fastapi[standard]>=0.115.12",
    "openai>=1.73.0",
    "pydantic-settings>=2.8.1",
]
